version: '3.7'

services:
  app:
    container_name: dw-graphql-dev
    build:
      context: .
      target: development
    image: dw-graphql-dev
    expose:
      - "9229"
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/src
    command: sh -c "sleep 3 && node scripts/addAdmin.js && yarn dev"

  db:
    image: postgres
    container_name: dw-db-dev
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
  
  adminer:
    image: adminer
    container_name: dw-adminer-dev
    restart: always
    ports:
      - 8080:8080
