version: '3.7'

services:
  app:
    container_name: dw-graphql
    build:
      context: .
      target: production
    image: dw-graphql
    expose:
      - "9229"
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/src
    command: yarn start

  db:
    image: postgres
    container_name: dw-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=production
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
